version: '{branch}-{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_branch_with_pr: true
image: Visual Studio 2017
init:
- ps: Install-Product node $env:nodejs_version
environment:
  nodejs_version: 8
install:
- ps: >-
    If (Test-Path Env:APPVEYOR_REPO_TAG_NAME) {
        ./gradlew clean -PjenkinsBuild -PreleaseType=DEV --continue --no-daemon
    } Else {
        ./gradlew clean -PjenkinsBuild --continue --no-daemon
    }
cache: C:\Users\appveyor\.gradle
build_script:
- ps: >-
    If (Test-Path Env:APPVEYOR_REPO_TAG_NAME) {
        ./gradlew build updateVersions updateAllDependencies -PjenkinsBuild -PreleaseType=DEV --continue --no-daemon
    } Else {
        ./gradlew build updateVersions updateAllDependencies -PjenkinsBuild --continue --no-daemon
    }

    if ($lastexitcode -ne 0) {
        throw ("Exec: " + $errorMessage)
    }

    cd vscode-wpilib

    npm install

    if ($lastexitcode -ne 0) {
        throw ("Exec: " + $errorMessage)
    }

    npm run compile

    if ($lastexitcode -ne 0) {
        throw ("Exec: " + $errorMessage)
    }

    npm run lint

    if ($lastexitcode -ne 0) {
        throw ("Exec: " + $errorMessage)
    }

    npm run gulp

    if ($lastexitcode -ne 0) {
        throw ("Exec: " + $errorMessage)
    }

    npm run webpack

    if ($lastexitcode -ne 0) {
        throw ("Exec: " + $errorMessage)
    }

    npm run vscePackage

    if ($lastexitcode -eq 0) {
        echo $lastexitcode
    }

    cd ..

    cd wpilib-utility-standalone

    npm install

    if ($lastexitcode -ne 0) {
        throw ("Exec: " + $errorMessage)
    }

    npm run lint

    if ($lastexitcode -ne 0) {
        throw ("Exec: " + $errorMessage)
    }

    npm run compile

    if ($lastexitcode -ne 0) {
        throw ("Exec: " + $errorMessage)
    }

    npm run packageWindows

    if ($lastexitcode -ne 0) {
        throw ("Exec: " + $errorMessage)
    }

    7z a WPILibStandalone.zip $env:APPVEYOR_BUILD_FOLDER\\build\\wpilibutility-win32-ia32\\*

    if ($lastexitcode -ne 0) {
        throw ("Exec: " + $errorMessage)
    }

test: off
artifacts:
- path: '**/*.vsix'
  name: VSIX
- path: '**/WPILibStandalone.zip'
  name: Standalone
deploy:
- provider: GitHub
  auth_token:
    secure: h4+50xyT4O2QudfUFvnjoUGSZUxNePY9WaYshTsaTzJctxhFFb21eERKx40qumep
  artifact: /.*\.*/
  on:
    appveyor_repo_tag: true
